{% set data = load_setup_py_data() %}

package:
  name: emat
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  number: 0
  script: "python -m pip install . --no-deps -vv"

requirements:
  host:
    - python>=3.7
    - pip
  run:
    - python>=3.7
    - numpy
    - pandas>=1.2
    - pydot
    - plotly>=4.14
    - scipy
    - seaborn
    - pyyaml
    - scikit-learn>=0.24
    - appdirs
    - matplotlib
    - graphviz
    - python-kaleido  # Plotly Static Image Export
    - ipywidgets
    - joblib
    - dask
    - distributed
    - cloudpickle
    - pytest
    - ipyparallel
    - pyzmq
    - platypus-opt
    - altair
    - salib
    - sqlalchemy
    - statsmodels
    - datashader
    - packaging

test:
  # Python imports
  imports:
    - emat

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - pytest
    - pytest-regressions

about:
  home: https://tmip-emat.github.io
  license: BSD
  license_file: LICENSE
  summary: exploratory modeling and analysis tools

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
